development: &development
  protocol: 'http'
  host: localhost
  port: 5984
  prefix: app42_paa_s_rails_couchdb_sample
  suffix: development
  username:
  password:

test:
  <<: *development
  suffix: test

production:
  protocol: 'http'                                               
  host: 192.168.2.202                  # VM IP
  port: 31761                  # VM Port
  prefix: t       # Database Name a/c to prefix and suffix 
#  suffix: production              # Database Name a/c to  prefix and suffix
  username: ayfb8a5t2dea7hqp         # User Name
  password: 'ae038nnyt9n043nzhgppz790gfi5v1bv'        # Password
